global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: ca-central-1
        port: 9100

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'